Add Torus Wagmi Connector
torusresearch/torus-wagmi-connector pull request #2
Opened 2022-09-30 14:18 UTC by yashovardhan

This PR adds the source code and demo for Torus Wagmi connector

2022-10-03 08:17 UTC, himanshuchawla009 commented
Test failing:-

1. Login 
2. It will show torus wallet button
3. Logout
4. Login
5. It won't show torus wallet button after login on bottom left, but it should show.

2022-10-07 20:42 UTC, yashovardhan commented
@himanshuchawla009 sorry for being late in implementing this fix. It was working for earlier but after clearing cache, it showed the same error as you mentioned.

I just added the fix for it.

2022-10-08 08:59 UTC, himanshuchawla009 requested changes

2022-10-08 08:59 UTC, himanshuchawla009 commented on src/lib/connector.ts
> +      if (this.torusOptions.TorusParams?.showTorusButton) {
fix case of TorusParams

2022-10-08 08:59 UTC, himanshuchawla009 commented on src/lib/connector.ts
> +      if (this.torusOptions.TorusParams?.showTorusButton) {
no need to showTorusButton like this , it will show by default.

2022-10-08 08:59 UTC, himanshuchawla009 commented on src/lib/connector.ts
> +            id: 0,
fix this ID thing, i have fixed in web3auth connector as well.
 Refer: https://github.com/Web3Auth/web3auth-wagmi-connector/pull/4

2022-10-08 08:59 UTC, himanshuchawla009 commented on src/lib/connector.ts
> +              id: 0,
fix chainId same as above

2022-10-08 08:59 UTC, himanshuchawla009 commented on src/lib/connector.ts
> +        return reject("error");
reject with a better error msg. Also listen to accountChanged event and await on that. isConnected might not be true immediately after login resolves,
so better to listen accountChanged event as well and thn resolve either on isConnected or accountsChanged trigger.

2022-10-11 04:06 UTC, yashovardhan commented on src/lib/connector.ts
> +      if (this.torusOptions.TorusParams?.showTorusButton) {
We trigger hide button after wagmi connector is disconnected. To remove the error you were facing earlier, this had to be done.

2022-10-11 04:10 UTC, yashovardhan commented on src/lib/connector.ts
> +            id: 0,
done

2022-10-11 04:10 UTC, yashovardhan commented on src/lib/connector.ts
> +              id: 0,
done

2022-11-21 16:46 UTC, YZhenY commented
can we release this @chaitanyapotti

2022-11-21 16:50 UTC, chaitanyapotti approved these changes
I see that my comments were implemented. lgtm

2022-11-21 16:50 UTC, merged